//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HonestBank.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
        }
    
        public int AccountID { get; set; }
        public Nullable<double> AvailableBalance { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<double> PendingBalance { get; set; }
        public string Status { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int HomeBranchID { get; set; }
        public int AssistingEmployeeID { get; set; }
        public string ProductCode { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
    }
}
